[project]
name = "imersao-dados-alura"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14.2"
dependencies = [
    "plotly>=6.5.2",
    "pycountry>=24.6.1",
    "streamlit>=1.53.1",
]
